name: 'Terraform CI/CD'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  TF_ROOT: "./"
  AWS_REGION: "us-east-1"

jobs:
  setup:
    name: Setup Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.5"

      - name: Clean Terraform Cache
        run: rm -rf .terraform .terraform.lock.hcl

      - name: Initialize Terraform
        run: terraform init -upgrade

      - name: Generate Terraform Lock File
        run: terraform providers lock -platform=linux_amd64

      - name: Save Terraform Workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: |
            .
            !terraform.tfstate
            !terraform.tfstate.backup

  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.5"

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.5"

      - name: Initialize Terraform
        run: terraform init

      - name: Remove Old Plan
        run: rm -f tfplan

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Verify tfplan File
        run: ls -lah tfplan || echo "⚠️ tfplan not found!"

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

  apply:
    name: Terraform Apply (Manual)
    runs-on: ubuntu-latest
    needs: plan
    environment: development
    steps:
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Verify tfplan File
        run: ls -lah tfplan || echo "⚠️ tfplan not found!"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.10.5"

      - name: Initialize Terraform
        run: terraform init -lockfile=readonly

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve tfplan
